export const users = [
  {
    id: 1,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 2,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 3,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 4,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 5,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 6,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 7,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 8,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 9,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 10,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 11,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 12,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 13,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 14,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 15,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 16,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 17,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 18,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 19,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
  {
    id: 20,
    login: 'DanLev',
    status: 'User',
    points: '20 000',
    complete: '49',
  },
]
